### ISSUE TITLE
@jwt_required throws error when brackets() is not used

### ISSUE THREAD

**Issue by sukanyabag** [tecladocode/flask-jwt-extended-section-lectures#1]
error message - TypeError: wrapper() got an unexpected keyword argument 'name'
python version - 3.9.10

On adding the brackets, everything works fine.

Any suggestions or reasons for this issue is appreciated.

**Comment by jslvtr** [comment]
Hey @sukanyabag ~~in Flask-JWT-Extended we don't need the brackets (I imagine you mean in the `@jwt_required()` decorator). Are you importing it from Flask-JWT by any chance?~~

/edit: 

I keep forgetting this was a change to Flask-JWT-Extended.

We do need the brackets now!

See the v4.0.0 breaking changes: https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/#api-changes

I will update the code in this repo.

**Comment by sukanyabag** [comment]
Thank you for the help @jslvtr !

**Comment by jslvtr** [comment]
No worries! That's the code updated now with 6eba040.
